import type Plyr from "plyr";

export const plyrI18n = {
  restart: "Start på nytt",
  rewind: "Spol {seektime}s tilbake",
  play: "Spill av",
  pause: "Pause",
  fastForward: "Spol {seektime}s frem",
  seek: "Søk",
  seekLabel: "{currentTime} av {duration}",
  played: "Spilt",
  buffered: "Bufret",
  currentTime: "Nåværende tid",
  duration: "Varighet",
  volume: "Volum",
  mute: "Demp",
  unmute: "Slå på lyd",
  enableCaptions: "Slå på undertekster",
  disableCaptions: "Slå av undertekster",
  download: "Last ned",
  enterFullscreen: "Fullskjerm",
  exitFullscreen: "Avslutt fullskjerm",
  frameTitle: "Spiller {title}",
  captions: "Undertekster",
  settings: "Innstillinger",
  pip: "Bilde-i-bilde",
  menuBack: "Tilbake",
  speed: "Hastighet",
  normal: "Normal",
  quality: "Kvalitet",
  loop: "Gjenta",
  start: "Start",
  end: "Slutt",
  all: "Alle",
  reset: "Nullstill",
  disabled: "Av",
  enabled: "På",
  advertisement: "Annonse",
  qualityBadge: {
    2160: "4K",
    1440: "HD",
    1080: "HD",
    720: "HD",
    576: "SD",
    480: "SD",
  },
};

export const plyrOptions: Plyr.Options = {
  controls: [
    "play-large",
    "play",
    "rewind",
    "fast-forward",
    "progress",
    "current-time",
    "duration",
    "mute",
    "volume",
    "fullscreen",
  ],
  seekTime: 10,
  hideControls: false,
  clickToPlay: true,
  keyboard: { focused: true, global: false },
  tooltips: { controls: true, seek: true },
  i18n: plyrI18n,
  loadSprite: true,
  iconUrl: "/plyr.svg",
};
